on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '*/15 * * * *'

name: pkgdown

jobs:
  render:
    name: Render vignette
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Install devtools
        run: Rscript -e 'install.packages("devtools")'
      - name: Render my document to all types
        run: Rscript -e 'rmarkdown::render("vignettes/vignette_ondetools.Rmd", output_format = "all")'
      - name: Commit results
        run: |
          git add docs/articles
          git commit -m 'Re-build vignette' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
